EF: variables and targets for LibreSSL added

diff --git a/t/Makefile.testssl b/t/Makefile.testssl
--- a/t/Makefile.testssl
+++ b/t/Makefile.testssl
@@ -145,6 +145,11 @@
 #?      Keep in mind that docker's "start" and "stop" have different behaviour.
 #?
 #? LIMITATIONS
+#?   %-run
+#?      There is no indication (status code, error message) when the configured
+#?      server fails to start. The only possibility is to check with:
+#?          docker ps --all
+#?
 #?   hostname
 #?      During build of the SSL-server, a hostname is set in the build image.
 #?      Unfortunately docker overwrites the hostname setting at end of each RUN
@@ -195,12 +200,22 @@
 # TODO
 #       List of feature, likes, etc. to be done in future:
 #
-#       * implement using files from https:/// or using git
-#       * implement checksum for files from http:...
-#       * implement %.dtls targets
+#       6/2024
+#       * build proper server.pem and install it (libressl)
+#       * build proper server.pem and install it (openssl)
+#       * provide variable TESTSSL.vm.server.env (to be pass with docker run)
 #       * wolfssl: use own instead of $TESTSSL.vm.configure.openssl
 #       * store all TESTSSL.sig.* in external Makefile to be included here;
 #         avoids editing this file for changes (wasting the repository)
+#       * provide variable TESTSSL.vm.server.cert (for building sef-signed cert)
+#       * implement general mechanism to use custom Makefile.testssl.VENDOR
+#         (vendor-specific settings should go away here, so we just have the
+#          functionality using defaults, special settings are in customizable
+#          included Makefiles)
+#       5/2024
+#       * implement using files from https:/// or using git
+#       * implement checksum for files from http:...
+#       * implement %.dtls targets
 #       * currently each brand and/or version builds its own docker image,
 #         provide a mode where they are all in the same image;
 #         ** user (in /etc/passwd) is already ok, just one for each brand
@@ -337,14 +352,14 @@
 #           du -h /|awk -F/ '(2==NF){print}'
 #?
 #? VERSION
-#?      @(#) ‘K\ 1.4 24/06/05 13:28:21
+#?      @(#) Då)c 1.5 24/06/05 17:23:00
 #?
 #? AUTHOR
 #?      24-mai-24 Achim Hoffmann
 #?
 # -----------------------------------------------------------------------------
 
-_SID.testssl       := 1.4
+_SID.testssl       := 1.5
 _MYSELF            := $(firstword $(MAKEFILE_LIST))
 
 # for user-defined arguments, see description in section LIMITATIONS above
@@ -448,8 +463,25 @@ TESTSSL.vm.configure.openssl =\
 	--enable-secure-renegotiation \
 	--enable-opensslall --enable-opensslextra \
 	--enable-lighty --enable-webclient --enable-earlydata
+TESTSSL.vm.configure.libressl =\
+	--prefix=$(TESTSSL.home)    --enable-static     \
+	--disable-option-checking   --disable-tests --enable-nc
 
 # define setting per brand (type) of SSL-/TLS-server (use brand's default)
+libressl-%:           TESTSSL.vm.type       = libressl
+libressl-%:           TESTSSL.vm.port       = 5443
+# default is 4433, but we want it different from mbedtls
+libressl-%:           TESTSSL.vm.packages  += $(TESTSSL.vm.apk.packages)
+libressl-%:           TESTSSL.vm.configure += $(TESTSSL.vm.configure.libressl)
+libressl-%:           TESTSSL.vm.client     = openssl
+libressl-%:           TESTSSL.vm.client.help= s_client help
+libressl-%:           TESTSSL.vm.server.help= s_server help
+libressl-%:           TESTSSL.vm.server.dtls= openssl s_server -dtls -key $(TESTSSL.vm.home)/etc/key.pm -cert $(TESTSSL.vm.home)/etc/cert.pm
+libressl-%:           TESTSSL.vm.server.tls = openssl
+libressl-%:           TESTSSL.vm.server.args= s_server -accept $(TESTSSL.vm.port) -WWW -www -key $(TESTSSL.vm.home)/etc/key.pem -cert $(TESTSSL.vm.home)/etc/cert.pem
+# TODO: s_server -servername $(TESTSSL.vm.hostname)
+# TODO: s_server -tls1_2 -tls1_3  # are both together possible?
+
 mbedtls-%:            TESTSSL.vm.type       = mbedtls
 mbedtls-%:            TESTSSL.vm.port       = 4433
 mbedtls-%:            TESTSSL.vm.packages  += gcc make musl-dev zlib-dev git
@@ -544,6 +576,10 @@ TESTSSL.vm.ALL  =\
 # TESTSSL.vm.context  not part of TESTSSL.vm.ALL; printed individually
 
 # SHA1 checksums for some tarballs:
+TESTSSL.sig.embedded-tls-0.17.0 = 2dfe66eecff5b3468ddb411890bb5642523c26b8
+TESTSSL.sig.libressl-3.8.3 = 9d39cd629255863689a5b9caab7b96f898119edf
+TESTSSL.sig.libressl-3.8.4 = 87fa0a43cf651e2ad58a56745fe9a486bbcddad2
+TESTSSL.sig.libressl-3.9.2 = e2397fd72dd3d213985a6309cd75de5c945bd035
 TESTSSL.sig.mbedtls-2.28.8 = 269c05f41ad53cc153c00b6506d16ac11727ebab
 TESTSSL.sig.mbedtls-2.7.8  = 0e8963cc159cb19c75ad51c4dfb9514b64daba97
 TESTSSL.sig.mbedtls-3.6.0  = 1175837831ac32c5f26c4113ea1a946db4822557
@@ -647,6 +683,11 @@ TESTSSL.vm.build.getpack = \
 	tar xf $(TESTSSL.vm.src.tar)      && \\ $(_NL)\
 	cd   \"\$$_dir\" && pwd && ls -l
 
+TESTSSL.vm.build.compile.libressl = \
+	test -x ./autogen.sh && ./autogen.sh || true && \\ $(_NL)\
+	./configure $(TESTSSL.vm.configure)  && \\ $(_NL)\
+	make
+
 TESTSSL.vm.build.compile.mbedtls = \
 	make no_test
 
@@ -659,6 +700,31 @@ TESTSSL.vm.build.compile = \
 	$(call _TESTSSL.echo,"Compile executables"); \\ $(_NL)\
 	pwd          && \\ $(_NL)\
 	$(TESTSSL.vm.build.compile.$(TESTSSL.vm.type))
+
+# TODO: starting liberssl's openssl fails with following error:
+#    Error configuring OpenSSL
+#    140300147796776:error:0EFFF071:configuration file \
+#       routines:CRYPTO_internal:unknown \
+#       module name:conf/conf_mod.c:196:module=providers
+# this happens even we've istalled openssl.cnf, but it seems to be incomplete
+# as workaround (6/2024) we use the environment variable OPENSSL_CONF  set to
+# the installed $(TESTSSL.vm.home)/etc/ssl/openssl.cnf
+# openssl seems to be happy with that
+TESTSSL.vm.build.install.libressl = \
+	mv apps/ocspcheck/ocspcheck $(TESTSSL.vm.home)/bin/ && \\ $(_NL)\
+	mv apps/openssl/openssl     $(TESTSSL.vm.home)/bin/ && \\ $(_NL)\
+	mv apps/nc/nc               $(TESTSSL.vm.home)/bin/ && \\ $(_NL)\
+	mv ssl/.libs/lib*.a         $(TESTSSL.vm.home)/bin/ && \\ $(_NL)\
+	mv ssl/.libs/lib*.so*       $(TESTSSL.vm.home)/bin/ && \\ $(_NL)\
+	mv tls/.libs/lib*.a         $(TESTSSL.vm.home)/bin/ && \\ $(_NL)\
+	mv tls/.libs/lib*.so*       $(TESTSSL.vm.home)/bin/ && \\ $(_NL)\
+	mv crypto/.libs/lib*.a      $(TESTSSL.vm.home)/bin/ && \\ $(_NL)\
+	mv crypto/.libs/lib*.so*    $(TESTSSL.vm.home)/bin/ && \\ $(_NL)\
+	mkdir -p $(TESTSSL.vm.home)/etc/ssl       &&  \\ $(_NL)\
+	mv openssl.cnf           $(TESTSSL.vm.home)/etc/ssl && \\ $(_NL)\
+	cd $(TESTSSL.vm.home)/etc/                &&  \\ $(_NL)\
+	export OPENSSL_CONF=$(TESTSSL.vm.home)/etc/ssl/openssl.cnf && \\ $(_NL)\
+	$(TESTSSL.vm.home)/bin/openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -sha256 -days 3650 -nodes -subj "/C=DE/ST=stateless/L=here/O=TESTSSL/OU=none/CN=127.0.0.1"
 
 # manuall installation keeps the original names of the executables, no mbedtls_ prefix
 TESTSSL.vm.build.install.mbedtls = \
@@ -693,9 +759,14 @@ TESTSSL.vm.build.install = \
 #	  $(TESTSSL.vm.build.install.$(TESTSSL.vm.type)) true)
 
 # optional
+TESTSSL.vm.build.testing.libressl = \
+	echo -n '\# number of ciphers $(TESTSSL.vm.client)):' ; \\ $(_NL)\
+	$(TESTSSL.vm.client) ciphers ALL:eNULL:kNULL |tr ':' ' ' | wc -w ; \\ $(_NL)\
+	$(TESTSSL.vm.client) ciphers ALL:eNULL:kNULL 
 TESTSSL.vm.build.testing.mbedtls = \
 	echo '\# mbedtls client does not list cipher suites'
 TESTSSL.vm.build.testing.wolfssl = \
+	export OPENSSL_CONF=$(TESTSSL.vm.home)/etc/ssl/openssl.cnf ; \\ $(_NL)\
 	echo -n '\# number of ciphers $(TESTSSL.vm.client)):' ; \\ $(_NL)\
         $(TESTSSL.vm.client) -e|tr ':' ' ' | wc -l ; \\ $(_NL)\
         $(TESTSSL.vm.client) -e
@@ -716,7 +787,7 @@ $(call _TESTSSL.gen-by,TESTSSL.vm.build.context)$(_NL)\
 FROM	$(TESTSSL.vm.from) AS testos            $(_NL)\
 COPY	$(TESTSSL.host.copy)/$(TESTSSL.vm.src.tar) $(TESTSSL.vm.tmp)/ $(_NL)\
         $(_NL)\
-LABEL	VERSION='1.4'                           $(_NL)\
+LABEL	VERSION='1.5'                           $(_NL)\
 LABEL	DESCRIPTION='docker image with $(TESTSSL.vm.from) for testing'$(_NL)\
         $(_NL)\
 RUN	\\  $(TESTSSL.vm.build.adduser)         $(_NL)\
@@ -732,7 +803,7 @@ $(call _TESTSSL.gen-by,TESTSSL.vm.build.server) $(_NL)\
 FROM	testos AS $(*)             $(_NL)\
         $(_NL)\
 LABEL	TESTSSL='$(TESTSSL.label)'              $(_NL)\
-LABEL	VERSION='1.4'                           $(_NL)\
+LABEL	VERSION='1.5'                           $(_NL)\
 LABEL	DESCRIPTION='docker image with $(*) for testing'$(_NL)\
 LABEL	USAGE_TCP='docker run --rm -p $(TESTSSL.host.port):$(TESTSSL.vm.port) $(_tag)' $(_NL)\
 ENV	TERM            xterm                   $(_NL)\
